name: eduapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  get: 4.6.5
  google_fonts: ^3.0.1
  json_annotation: ^4.6.0
  json_serializable: ^6.3.1
  lottie: ^1.4.2
  otp_text_field: ^1.1.3

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  lints: 2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/lottie/
  fonts:
    - family: Logos
      fonts:
        - asset: "assets/icons/Logos.ttf"
